Refactor various things
regression_analysis: simplify flow and remove useless branches;
utils: rename parameters in chunkify;
exception: simplify exceptions;
streams: fix issue with unsafe yaml;
git: remove useless catch-clauses.