Update `statsmodels` package version
The old version (0.9.0) caused the following error:
  ImportError: cannot import name 'factorial'
It is related to the change of the `scipy` package
version and incompatibility between these packages.