Fix various issues
cli: rename utils to utils_group (clash of names);
various: remove useless asserts;
decorators: remove useless decorator;
exception: add new exception;
script_helpers: add autoescaping of templates (security issue);
test_store: add basic tests of store.